### ISSUE TITLE
Implement input and Inputs

### ISSUE THREAD

**Issue by MiSawa** [MiSawa/xq#116]

**Comment by itchyny** [comment]
Note that the `inputs` filter is often used with `-n` to reduce all the input values.
```sh
❯ jq -n 'reduce inputs as $x (0; . + $x)' <<< '1 2 3 4 5'
15

❯ jq 'reduce inputs as $x (0; . + $x)' <<< '1 2 3 4 5' 
14

❯ xq -n 'reduce inputs as $x (0; . + $x)' <<< '1 2 3 4 5'
0

❯ xq 'reduce inputs as $x (0; . + $x)' <<< '1 2 3 4 5' 
14

❯ xq --version                                           
xq 0.2.21-111ca589af6ab3cf3f32bfa6c041a05f1eb0189f
```

**Comment by MiSawa** [comment]
Ah what...?? That looks really useful, but I don't understand the semantics of `-n` then..... :thinking:

**Comment by wader** [comment]
for https://github.com/wader/fq i implemented it by a global array of files to read, `input` reads/decodes on file, `inputs` repets `input` and then let the `-n` flag decide if if first input should be `input` or `null`. I guess for jq it's a bit more complicated as one file can have multiple JSON values or on value cab span multiple files as i understand it.

**Comment by MiSawa** [comment]
Thanks, yeah it doesn't seem to be the case for jq as you mentioned... though I think I figured out in #120.

**Comment by wader** [comment]
Nice! and also nice to see all the progress on xq
