### ISSUE TITLE
Panics on comparison of booleans

### ISSUE THREAD

**Issue by itchyny** [MiSawa/xq#15]
Comparison on booleans panics.

```sh
 $ xq -n 'false < true'
thread 'main' panicked at 'internal error: entered unreachable code', src/intrinsic/comparator.rs:99:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

xq: 0.1.0-d3808e624efc78b26ebd3c464bea59132f83aec8

**Comment by MiSawa** [comment]
Oooops, Nice find! This is a bug I introduced while I was changing `Value::True` and `Value::False` to `Value::Boolean(bool)`.
