### ISSUE TITLE
limit does not terminate on infinite stream

### ISSUE THREAD

**Issue by itchyny** [MiSawa/xq#28]
Curren xq does not terminate on limiting infinite stream. But it should terminate on emitting the specified number of values.
```sh
❯ xq --version
xq 0.1.4-2144efcf48e5915206d1b6083ef21f6ec752efb3

❯ xq -n 'limit(3; repeat(0))' 
0
0
0
^C
```

**Comment by MiSawa** [comment]
Good catch! Fixed `any` and `all` as well as `limit`.
